name: Generate PEH Model Artefacts

permissions:
  contents: write
  pull-requests: write 

on:
  pull_request:
    paths:
      - '.github/workflows/artefacts.yaml'
      - 'linkml/schema/**'
  push:
    branches:
      - main
    paths:
      - 'linkml/schema/**'

jobs:
  generate-artefacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install "linkml>=1.9,<2" black toml

      - name: Create necessary directories
        run: |
          make make-dirs

      - name: Generate project artifacts
        run: |
          make gen-project

      - name: Sync pyproject.toml with schema version
        run: |
          make sync-version

      - name: Commit and push changes if on main branch
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Check if there are changes to commit
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          git add linkml/jsonld/ linkml/owl/ linkml/rdf/ linkml/src/peh_model/
          git commit -m "Auto-generate model artifacts [skip ci]"
          
          # Use token to push changes
          git push